import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import FormAddClient from '../components/FormAddClient'
import Table from '../components/Table'
import { IUser } from '../dto/IUser'

interface IRes {
  users: IUser[]
}

const Home: NextPage = () => {
  const [users, setUsers] = useState<IUser[]>([]);

  const getUsers = async () => {
    try {
      const res = await fetch('/api/users');
      const data: IRes = await res.json();

      setUsers(data.users);
    }
    catch (err) {
      console.error(err);
    }
  }

  useEffect(() => {
    getUsers();
  }, []);

  return (
    <div>
      <Head>
        <title>CRUD Clientes - 2Play+</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col items-center py-6'>
        <h1 className='text-3xl text-orange-500'>CRUD Clientes</h1>

        <FormAddClient />

        <Table users={users} />
      </main>
    </div>
  )
}

export default Home
